//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaveTech.Scutex.Providers.WebServicesProvider.WcfServices.ReportingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfServices.ReportingService.IReportingService")]
    public interface IReportingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportingService/GetAllActivationLogs", ReplyAction="http://tempuri.org/IReportingService/GetAllActivationLogsResponse")]
        string GetAllActivationLogs(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportingService/GetAllLicenseActivations", ReplyAction="http://tempuri.org/IReportingService/GetAllLicenseActivationsResponse")]
        string GetAllLicenseActivations(string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportingServiceChannel : WaveTech.Scutex.Providers.WebServicesProvider.WcfServices.ReportingService.IReportingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportingServiceClient : System.ServiceModel.ClientBase<WaveTech.Scutex.Providers.WebServicesProvider.WcfServices.ReportingService.IReportingService>, WaveTech.Scutex.Providers.WebServicesProvider.WcfServices.ReportingService.IReportingService {
        
        public ReportingServiceClient() {
        }
        
        public ReportingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAllActivationLogs(string token) {
            return base.Channel.GetAllActivationLogs(token);
        }
        
        public string GetAllLicenseActivations(string token) {
            return base.Channel.GetAllLicenseActivations(token);
        }
    }
}
