// <copyright file="when_validating_a_single_key.should_work_when_using_valid_key.g.cs" company="WaveTech Digital Technologies, Inc.">Copyright © WaveTech Digital Technologies, Inc. 2009-2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace WaveTech.Scutex.UnitTests.Generators.SmallStaticKeyGeneratorTests
{
	public partial class when_validating_a_single_key
	{
	}
}
