// <copyright file="when_using_the_key_value_deobfuscator.should_be_5_with_char_of_R_and_weights_of_6_and_3.g.cs" company="WaveTech Digital Technologies, Inc.">Copyright © WaveTech Digital Technologies, Inc. 2009-2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace WaveTech.Scutex.UnitTests.Generators.SmallStaticKeyGeneratorTests
{
	public partial class when_using_the_key_value_deobfuscator
	{
[TestMethod]
[PexGeneratedBy(typeof(when_using_the_key_value_deobfuscator))]
public void should_be_5_with_char_of_R_and_weights_of_6_and_301()
{
    this.should_be_5_with_char_of_R_and_weights_of_6_and_3();
}
	}
}
