//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaveTech.Scutex.Manager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaveTech.Scutex.Manager.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Licenses.
        /// </summary>
        public static string ApplicationMenu_RecentItems_Header {
            get {
                return ResourceManager.GetString("ApplicationMenu_RecentItems_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Shared_ApplicationMenu_Button_Close {
            get {
                return ResourceManager.GetString("Shared_ApplicationMenu_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Shared_ApplicationMenu_Button_Exit {
            get {
                return ResourceManager.GetString("Shared_ApplicationMenu_Button_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Shared_ApplicationMenu_Button_New {
            get {
                return ResourceManager.GetString("Shared_ApplicationMenu_Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Shared_ApplicationMenu_Button_Open {
            get {
                return ResourceManager.GetString("Shared_ApplicationMenu_Button_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Shared_ApplicationMenu_Button_Save {
            get {
                return ResourceManager.GetString("Shared_ApplicationMenu_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Tab_Database_Header {
            get {
                return ResourceManager.GetString("Tab_Database_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Tab_Group_Help_Button_About {
            get {
                return ResourceManager.GetString("Tab_Group_Help_Button_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Tab_Group_Help_Button_Help {
            get {
                return ResourceManager.GetString("Tab_Group_Help_Button_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string Tab_Group_Help_Button_Homepage {
            get {
                return ResourceManager.GetString("Tab_Group_Help_Button_Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Tab_Group_Help_Caption {
            get {
                return ResourceManager.GetString("Tab_Group_Help_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Tab_Group_Home_Button_Close {
            get {
                return ResourceManager.GetString("Tab_Group_Home_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Tab_Group_Home_Button_New {
            get {
                return ResourceManager.GetString("Tab_Group_Home_Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Tab_Group_Home_Button_Open {
            get {
                return ResourceManager.GetString("Tab_Group_Home_Button_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Tab_Group_Home_Button_Save {
            get {
                return ResourceManager.GetString("Tab_Group_Home_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Tab_Group_Home_Caption {
            get {
                return ResourceManager.GetString("Tab_Group_Home_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Integration.
        /// </summary>
        public static string Tab_Group_Licensing_Button_Code {
            get {
                return ResourceManager.GetString("Tab_Group_Licensing_Button_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Keys.
        /// </summary>
        public static string Tab_Group_Licensing_Button_Generate {
            get {
                return ResourceManager.GetString("Tab_Group_Licensing_Button_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Tab_Group_Licensing_Caption {
            get {
                return ResourceManager.GetString("Tab_Group_Licensing_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product.
        /// </summary>
        public static string Tab_Group_ProductsGeneral_Button_Edit {
            get {
                return ResourceManager.GetString("Tab_Group_ProductsGeneral_Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Product.
        /// </summary>
        public static string Tab_Group_ProductsGeneral_Button_New {
            get {
                return ResourceManager.GetString("Tab_Group_ProductsGeneral_Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Product.
        /// </summary>
        public static string Tab_Group_ProductsGeneral_Button_Remove {
            get {
                return ResourceManager.GetString("Tab_Group_ProductsGeneral_Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Logs.
        /// </summary>
        public static string Tab_Group_ServiceManagement_Button_Download {
            get {
                return ResourceManager.GetString("Tab_Group_ServiceManagement_Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Service.
        /// </summary>
        public static string Tab_Group_ServiceManagement_Button_New {
            get {
                return ResourceManager.GetString("Tab_Group_ServiceManagement_Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Service.
        /// </summary>
        public static string Tab_Group_ServiceManagement_Button_Remove {
            get {
                return ResourceManager.GetString("Tab_Group_ServiceManagement_Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Service.
        /// </summary>
        public static string Tab_Group_ServiceManagement_Button_Update {
            get {
                return ResourceManager.GetString("Tab_Group_ServiceManagement_Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Products.
        /// </summary>
        public static string Tab_Group_ServiceManagement_Button_Upload {
            get {
                return ResourceManager.GetString("Tab_Group_ServiceManagement_Button_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Keys.
        /// </summary>
        public static string Tab_Group_ServiceManagement_Button_UploadKeys {
            get {
                return ResourceManager.GetString("Tab_Group_ServiceManagement_Button_UploadKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Services.
        /// </summary>
        public static string Tab_Group_ServiceManagement_Button_ViewServices {
            get {
                return ResourceManager.GetString("Tab_Group_ServiceManagement_Button_ViewServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string Tab_Group_ServiceManagement_Text {
            get {
                return ResourceManager.GetString("Tab_Group_ServiceManagement_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Code.
        /// </summary>
        public static string Tab_Group_System_Button_GenerateCode {
            get {
                return ResourceManager.GetString("Tab_Group_System_Button_GenerateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Tab_Group_System_Button_Products {
            get {
                return ResourceManager.GetString("Tab_Group_System_Button_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Demo.
        /// </summary>
        public static string Tab_Group_System_Button_Test {
            get {
                return ResourceManager.GetString("Tab_Group_System_Button_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Tab_Group_System_Button_Validate {
            get {
                return ResourceManager.GetString("Tab_Group_System_Button_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Tab_Group_System_Caption {
            get {
                return ResourceManager.GetString("Tab_Group_System_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Tab_Home_Header {
            get {
                return ResourceManager.GetString("Tab_Home_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Tab_Products_Header {
            get {
                return ResourceManager.GetString("Tab_Products_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Code.
        /// </summary>
        public static string Tab_ProductsCode_Header {
            get {
                return ResourceManager.GetString("Tab_ProductsCode_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Tab_ProductsGeneral_Header {
            get {
                return ResourceManager.GetString("Tab_ProductsGeneral_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Tab_Services_Header {
            get {
                return ResourceManager.GetString("Tab_Services_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Tab_ServicesGeneral_Header {
            get {
                return ResourceManager.GetString("Tab_ServicesGeneral_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Tab_ServicesManagement_Header {
            get {
                return ResourceManager.GetString("Tab_ServicesManagement_Header", resourceCulture);
            }
        }
    }
}
