ALTER TABLE [dbo].[DBVersions]
    ADD CONSTRAINT [PK_DBVersions] PRIMARY KEY CLUSTERED ([DBVersionId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

