ALTER TABLE [dbo].[Features]
    ADD CONSTRAINT [PK_Features] PRIMARY KEY CLUSTERED ([FeatureId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

