ALTER TABLE [dbo].[LicenseSetFeatures]
    ADD CONSTRAINT [PK_LicenseSetFeatures] PRIMARY KEY CLUSTERED ([LicenseSetFeatureId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

