ALTER TABLE [dbo].[ProductEditions]
    ADD CONSTRAINT [PK_ProductEditions] PRIMARY KEY CLUSTERED ([ProductEditionId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

