ALTER TABLE [dbo].[ProductVersions]
    ADD CONSTRAINT [PK_ProductVersions] PRIMARY KEY CLUSTERED ([ProductVersionId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

