ALTER TABLE [dbo].[TrialExpirationOptions]
    ADD CONSTRAINT [PK_TrialExpirationOptions] PRIMARY KEY CLUSTERED ([TrialExpirationOptionId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

