ALTER TABLE [dbo].[TrialSettings]
    ADD CONSTRAINT [PK_TrialSettings] PRIMARY KEY CLUSTERED ([TrialSettingId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

