ALTER TABLE [dbo].[LicenseKeys]
    ADD CONSTRAINT [PK_LicenseKeys] PRIMARY KEY CLUSTERED ([LicenseKeyId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

