ALTER TABLE [dbo].[Licenses]
    ADD CONSTRAINT [PK_Licenses] PRIMARY KEY CLUSTERED ([LicenseId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

