ALTER TABLE [dbo].[LicenseSets]
    ADD CONSTRAINT [PK_LicenseSets] PRIMARY KEY CLUSTERED ([LicenseSetId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

