ALTER TABLE [dbo].[Master]
    ADD CONSTRAINT [PK_Master] PRIMARY KEY CLUSTERED ([MasterId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

