//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaveTech.Scutex.Providers.WmiDataProvider.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaveTech.Scutex.Providers.WmiDataProvider.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win32_BIOS.
        /// </summary>
        internal static string Wmi_Bios {
            get {
                return ResourceManager.GetString("Wmi_Bios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Wmi_Bios_Name {
            get {
                return ResourceManager.GetString("Wmi_Bios_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Wmi_Bios_Version {
            get {
                return ResourceManager.GetString("Wmi_Bios_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win32_MemoryDevice.
        /// </summary>
        internal static string Wmi_Memory {
            get {
                return ResourceManager.GetString("Wmi_Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win32_BaseBoard.
        /// </summary>
        internal static string Wmi_Motherboard {
            get {
                return ResourceManager.GetString("Wmi_Motherboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string Wmi_Motherboard_Manufacturer {
            get {
                return ResourceManager.GetString("Wmi_Motherboard_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Wmi_Motherboard_Sku {
            get {
                return ResourceManager.GetString("Wmi_Motherboard_Sku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string Wmi_Motherboard_Tag {
            get {
                return ResourceManager.GetString("Wmi_Motherboard_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Wmi_Motherboard_Version {
            get {
                return ResourceManager.GetString("Wmi_Motherboard_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win32_Processor.
        /// </summary>
        internal static string Wmi_Processsor {
            get {
                return ResourceManager.GetString("Wmi_Processsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string Wmi_Processsor_Manufacturer {
            get {
                return ResourceManager.GetString("Wmi_Processsor_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessorId.
        /// </summary>
        internal static string Wmi_Processsor_ProcessorId {
            get {
                return ResourceManager.GetString("Wmi_Processsor_ProcessorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SocketDesignation.
        /// </summary>
        internal static string Wmi_Processsor_SocketDesignation {
            get {
                return ResourceManager.GetString("Wmi_Processsor_SocketDesignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Wmi_Processsor_Version {
            get {
                return ResourceManager.GetString("Wmi_Processsor_Version", resourceCulture);
            }
        }
    }
}
